FROM nvcr.io/nvidia/pytorch:25.03-py3

RUN pip install --no-cache-dir \
    transformers \
    datasets \
    mlflow \
    onnx

COPY ml/train.py /app/train.py
WORKDIR /app

ENTRYPOINT ["python", "train.py"]
